
CREATE TABLE BALLOT (ID INTEGER NOT NULL, CREATED_AT TIMESTAMP WITH TIME ZONE, CREATED_BY VARCHAR(70), MODIFIED_AT TIMESTAMP WITH TIME ZONE, MODIFIED_BY VARCHAR(70), HELD_AT DATE NOT NULL, BALLOTNAME VARCHAR(255) NOT NULL, POLL_CLOSED TIMESTAMP WITH TIME ZONE, POLL_OPENED TIMESTAMP WITH TIME ZONE, BALLOT_STATUS VARCHAR(20) NOT NULL, OPTLOCK INTEGER, PRIMARY KEY (ID));
CREATE TABLE BALLOT_NOMINEE (ID INTEGER NOT NULL, CREATED_AT TIMESTAMP WITH TIME ZONE, CREATED_BY VARCHAR(70), MODIFIED_AT TIMESTAMP WITH TIME ZONE, MODIFIED_BY VARCHAR(70), NOMINEE_NAME VARCHAR(255) NOT NULL, SHORTKEY VARCHAR(3), OPTLOCK INTEGER, BALLOT_ID INTEGER, PRIMARY KEY (ID));
CREATE TABLE BALLOT_USER (ID INTEGER NOT NULL, CREATED_AT TIMESTAMP WITH TIME ZONE, CREATED_BY VARCHAR(70), MODIFIED_AT TIMESTAMP WITH TIME ZONE, MODIFIED_BY VARCHAR(70), isAdmin BOOL NOT NULL, isCounter BOOL NOT NULL, name VARCHAR(255), USERID VARCHAR(70) NOT NULL, OPTLOCK INTEGER, BALLOT_ID INTEGER, PRIMARY KEY (ID), CONSTRAINT UC_USER UNIQUE (BALLOT_ID, USERID));
CREATE TABLE BALLOT_VOTE (ID INTEGER NOT NULL, CREATED_AT TIMESTAMP WITH TIME ZONE, CREATED_BY VARCHAR(70), MODIFIED_AT TIMESTAMP WITH TIME ZONE, MODIFIED_BY VARCHAR(70), CASTED_VOTES VARCHAR(4000), INVALID_REASON VARCHAR(255), VOTE_NR INTEGER NOT NULL, OPTLOCK INTEGER, BALLOT_ID INTEGER, PRIMARY KEY (ID), CONSTRAINT U_VOTENR UNIQUE (BALLOT_ID, VOTE_NR));
CREATE TABLE SEQUENCES (ID VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
ALTER TABLE BALLOT_NOMINEE ADD FOREIGN KEY (BALLOT_ID) REFERENCES BALLOT (ID) DEFERRABLE;
ALTER TABLE BALLOT_USER ADD FOREIGN KEY (BALLOT_ID) REFERENCES BALLOT (ID) DEFERRABLE;
ALTER TABLE BALLOT_VOTE ADD FOREIGN KEY (BALLOT_ID) REFERENCES BALLOT (ID) DEFERRABLE;
