CREATE TABLE Ballot (id INTEGER NOT NULL, heldAt DATE NOT NULL, name VARCHAR(255) NOT NULL, pollClosed TIMESTAMP WITH TIME ZONE, pollOpened TIMESTAMP WITH TIME ZONE, status VARCHAR(20) NOT NULL, optLock INTEGER, PRIMARY KEY (id));
CREATE TABLE BallotNominee (id INTEGER NOT NULL, name VARCHAR(255), optLock INTEGER, BALLOT_ID INTEGER, PRIMARY KEY (id));
CREATE TABLE BallotUser (id INTEGER NOT NULL, isAdmin BOOLEAN NOT NULL, isCounter BOOLEAN NOT NULL, name VARCHAR(255), userId VARCHAR(70) NOT NULL, optLock INTEGER, BALLOT_ID INTEGER, PRIMARY KEY (id));
CREATE TABLE BallotVote (id INTEGER NOT NULL, createdAt TIMESTAMP WITH TIME ZONE, createdBy VARCHAR(70), nominees VARCHAR(4000), optLock INTEGER, BALLOT_ID INTEGER, PRIMARY KEY (id));
CREATE TABLE SEQUENCES (ID VARCHAR(255) NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
ALTER TABLE BallotNominee ADD FOREIGN KEY (BALLOT_ID) REFERENCES Ballot (id);
ALTER TABLE BallotUser ADD FOREIGN KEY (BALLOT_ID) REFERENCES Ballot (id);
ALTER TABLE BallotVote ADD FOREIGN KEY (BALLOT_ID) REFERENCES Ballot (id);
